-- Split on purpose. Neon and Tiger are both Postgres, and they do different jobs.
--
--   schema/neon.sql   profiles, shelf, rescue history, recipe history
--   schema/tiger.sql  waste_events hypertable + impact_daily continuous aggregate
--
-- Apply them with:
--   npm run db:neon
--   npm run db:tiger
--
-- Booth mode does not use either file. With no connection strings, the same
-- waste_events shape lives in local PGlite so the Impact page still draws.
