// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  hosting: __t.bool(),
  scriptIndex: __t.u32().name("script_index"),
  lastScriptAtMs: __t.i64().name("last_script_at_ms"),
  nextId: __t.u32().name("next_id"),
  toastId: __t.option(__t.string()).name("toast_id"),
  toastTitle: __t.option(__t.string()).name("toast_title"),
  toastBody: __t.option(__t.string()).name("toast_body"),
});
