// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  quantityLabel: __t.string().name("quantity_label"),
  grams: __t.f64(),
  category: __t.string(),
  priceUsd: __t.f64().name("price_usd"),
  expiresAtMs: __t.i64().name("expires_at_ms"),
  addedAtMs: __t.i64().name("added_at_ms"),
  source: __t.string(),
  state: __t.string(),
  note: __t.option(__t.string()),
  safety: __t.option(__t.string()),
  fromName: __t.option(__t.string()).name("from_name"),
  eventId: __t.option(__t.string()).name("event_id"),
});
