// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  ingredientId: __t.option(__t.string()).name("ingredient_id"),
  name: __t.string(),
  quantityLabel: __t.string().name("quantity_label"),
  grams: __t.f64(),
  category: __t.string(),
  priceUsd: __t.f64().name("price_usd"),
  expiresAtMs: __t.i64().name("expires_at_ms"),
  poster: __t.string(),
  postedAtMs: __t.i64().name("posted_at_ms"),
  note: __t.string(),
  safety: __t.option(__t.string()),
  claimedBy: __t.option(__t.string()).name("claimed_by"),
  claimedAtMs: __t.option(__t.i64()).name("claimed_at_ms"),
});
