// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  atMs: __t.i64().name("at_ms"),
  kind: __t.string(),
  name: __t.string(),
  grams: __t.f64(),
  category: __t.string(),
  priceUsd: __t.f64().name("price_usd"),
  co2EKg: __t.f64().name("co_2_e_kg"),
  methaneEmittedKg: __t.f64().name("methane_emitted_kg"),
  embodiedCo2EKg: __t.f64().name("embodied_co_2_e_kg"),
  waterL: __t.f64().name("water_l"),
});
