// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddIngredientsReducer from "../add_ingredients_reducer";
import ClaimReducer from "../claim_reducer";
import HostReducer from "../host_reducer";
import KeepAliveReducer from "../keep_alive_reducer";
import LogMealReducer from "../log_meal_reducer";
import MarkReducer from "../mark_reducer";
import OfferReducer from "../offer_reducer";
import ResetReducer from "../reset_reducer";
import TickReducer from "../tick_reducer";

export type AddIngredientsParams = __Infer<typeof AddIngredientsReducer>;
export type ClaimParams = __Infer<typeof ClaimReducer>;
export type HostParams = __Infer<typeof HostReducer>;
export type KeepAliveParams = __Infer<typeof KeepAliveReducer>;
export type LogMealParams = __Infer<typeof LogMealReducer>;
export type MarkParams = __Infer<typeof MarkReducer>;
export type OfferParams = __Infer<typeof OfferReducer>;
export type ResetParams = __Infer<typeof ResetReducer>;
export type TickParams = __Infer<typeof TickReducer>;

